openapi: 3.0.0
info:
  title: Service Dependency Api
  version: 1.0.0
tags:
  - name: Dependencies
    description: Calls about linking services
  - name: Releases
    description: Release Management for a service
  - name: Services
    description: Service Management
  - name: System
    description: System Check Calls
paths:
  /services/:id/dependency:
    post:
      summary: Create dependency
      operationId: Create dependency
      description: ''
      tags:
        - Dependencies
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: 05c980e5-cb47-4659-bd2b-2a72371c1b79
      requestBody:
        $ref: '#/components/requestBodies/create_dependency'
  /services/:id/dependency/:targetId:
    delete:
      summary: Delete dependency
      operationId: Delete dependency
      description: ''
      tags:
        - Dependencies
      responses:
        '200':
          description: ''
      parameters:
        - name: targetId
          in: query
          description: ''
          required: true
          example: 05c980e5-cb47-4659-bd2b-2a72371c1b79
        - name: id
          in: query
          description: ''
          required: true
          example: 5931d4b0-dd0a-4654-85fe-78f42890da0d
  /services/:id/dependencies:
    get:
      summary: Dependencies for a service
      operationId: Dependencies for a service
      description: ''
      tags:
        - Dependencies
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: 5931d4b0-dd0a-4654-85fe-78f42890da0d
  /services/:id/dependents:
    get:
      summary: Dependents on service
      operationId: Dependents on service
      description: ''
      tags:
        - Dependencies
      responses:
        '200':
          description: ''
      parameters:
        - name: version
          in: query
          description: ''
          required: false
          example: 1.5.0
        - name: id
          in: query
          description: ''
          required: true
          example: 12973952-0165-400b-9178-a0fdbd90f967
  /services/:serviceId/release:
    post:
      summary: Create Release
      operationId: Create Release
      description: ''
      tags:
        - Releases
      responses:
        '200':
          description: ''
      parameters:
        - name: serviceId
          in: query
          description: ''
          required: true
          example: 5931d4b0-dd0a-4654-85fe-78f42890da0d
      requestBody:
        $ref: '#/components/requestBodies/create_release'
  /services/:id/releases:
    get:
      summary: Releases For Service
      operationId: Releases For Service
      description: ''
      tags:
        - Releases
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: 5931d4b0-dd0a-4654-85fe-78f42890da0d
  /releases/:startDate/:endDate:
    get:
      summary: Releases In Date Range
      operationId: Releases In Date Range
      description: ''
      tags:
        - Releases
      responses:
        '200':
          description: ''
      parameters:
        - name: startDate
          in: query
          description: ''
          required: true
          example: '2025-05-04'
        - name: endDate
          in: query
          description: ''
          required: true
          example: '2025-05-06'
  /services:
    post:
      summary: Create service
      operationId: Create service
      description: ''
      tags:
        - Services
      responses:
        '200':
          description: ''
      requestBody:
        $ref: '#/components/requestBodies/create_service'
    get:
      summary: List all services
      operationId: List all services
      description: ''
      tags:
        - Services
      responses:
        '200':
          description: ''
      parameters:
        - name: page
          in: query
          description: ''
          required: true
          example: '1'
        - name: pageSize
          in: query
          description: ''
          required: true
          example: '10'
  /services/:id:
    delete:
      summary: Delete Service
      operationId: Delete Service
      description: ''
      tags:
        - Services
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: 05c980e5-cb47-4659-bd2b-2a72371c1b79
    get:
      summary: Get service by id
      operationId: Get service by id
      description: ''
      tags:
        - Services
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: 5931d4b0-dd0a-4654-85fe-78f42890da0d
    put:
      summary: Update Service
      operationId: Update Service
      description: ''
      tags:
        - Services
      responses:
        '200':
          description: ''
      parameters:
        - name: id
          in: query
          description: ''
          required: true
          example: 5931d4b0-dd0a-4654-85fe-78f42890da0d
      requestBody:
        $ref: '#/components/requestBodies/update_service'
  /database:
    get:
      summary: Database URL
      operationId: Database URL
      description: ''
      tags:
        - System
      responses:
        '200':
          description: ''
  /helloworld:
    get:
      summary: Hello World
      operationId: Hello World
      description: ''
      tags:
        - System
      responses:
        '200':
          description: ''
      parameters:
        - name: name
          in: query
          description: ''
          required: false
          example: user
  /time:
    get:
      summary: Time
      operationId: Time
      description: ''
      tags:
        - System
      responses:
        '200':
          description: ''
servers:
  - url: http://localhost:8080
components:
  schemas:
    create_dependency:
      type: object
      properties:
        id:
          type: string
        version:
          type: string
    create_release:
      type: object
      properties:
        url:
          type: string
        version:
          type: string
        release_date:
          type: string
    create_service:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        description:
          type: string
        url:
          type: string
    update_service:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
        description:
          type: string
        url:
          type: string
  requestBodies:
    create_dependency:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create_dependency'
      description: ''
      required: true
    create_release:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create_release'
      description: ''
      required: true
    create_service:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create_service'
      description: ''
      required: true
    update_service:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/update_service'
      description: ''
      required: true
  securitySchemes: {}
